export const tariffs = [
  {
    name: "Get Started",
    title: "Developer",
    type: "start",
    description: "",
    price: "Free",
    priceSuffix: "",
    buttonText: "Start for Free",
    featuresBeforeLine: ["Up to 100 MAUs", "1 self-hosted runtime"],
    featuresAfterLine: [
      "Core CopilotKit",
      "CoAgents",
      "Cloud hosted",
      "Discord community support",
    ],
  },
  {
    name: "Pro",
    type: "pro",
    title: "Teams",
    description: "/month",
    price: "$249",
    priceSuffix: "/month",
    buttonText: "Build With Your Team",
    featuresBeforeLine: ["Up to 1000 MAUs", "3 self-hosted runtimes"],
    plusTitle: "Everything in Developer plus:",
    featuresAfterLine: [
      "Team accounts",
      "Onboarding consultation, dedicated Slack support and SLA",
    ],
  },
  {
    name: "Enterprise",
    type: "enterprise",
    title: "Scale",
    description: "",
    price: "Contact Us",
    priceSuffix: "",
    buttonText: "Get a Custom Plan",
    featuresBeforeLine: ["Custom plans"],
    plusTitle: "Everything in Pro plus:",
    featuresAfterLine: [
      "SSO",
      "On-prem Cloud",
      "Internationalization",
      "Accessibility support",
      "Onboarding consultation, dedicated Slack support and SLA",
    ],
  },
];
